<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoFixture" Version="4.18.1" />
      <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
      <PackageReference Include="Bogus" Version="35.6.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\x86cc.Benchmarks.Common\x86cc.Benchmarks.Common.csproj" />
    </ItemGroup>

</Project>
