<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
        <PackageReference Include="Bogus" Version="35.6.5" />
        <PackageReference Include="Testcontainers" Version="4.14.0" />
        <PackageReference Include="StackExchange.Redis" Version="3.1.31" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\x86cc.Benchmarks.Common\x86cc.Benchmarks.Common.csproj" />
    </ItemGroup>

</Project>
