<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
        <PackageReference Include="Autofac" Version="9.0.0" />
        <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
        <PackageReference Include="Autofac.Extras.DynamicProxy" Version="7.1.0" />
        <PackageReference Include="Caliburn.Micro.Container" Version="1.5.2" />
        <PackageReference Include="Caliburn.Micro.Core" Version="5.0.258" />
        <PackageReference Include="Castle.Windsor" Version="6.0.0" />
        <PackageReference Include="DryIoc.dll" Version="5.4.3" />
        <PackageReference Include="DryIoc.Microsoft.DependencyInjection" Version="6.2.0" />
        <PackageReference Include="DryIocZero" Version="4.0.0" />
        <PackageReference Include="Lamar" Version="15.0.1" />
        <PackageReference Include="MicroResolver" Version="2.3.5" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Spring.Aop" Version="3.0.3" />
        <PackageReference Include="Spring.Core" Version="3.0.3" />
        <PackageReference Include="Stashbox" Version="5.17.1" />
        <PackageReference Include="Stashbox.Extensions.Dependencyinjection" Version="5.7.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\x86cc.Benchmarks.Common\x86cc.Benchmarks.Common.csproj" />
    </ItemGroup>

</Project>
