<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
        <PackageReference Include="Bogus" Version="35.6.5" />
        <PackageReference Include="MongoDB.Driver" Version="3.11.1" />
        <PackageReference Include="Marten" Version="9.30.0" />
        <PackageReference Include="Oracle.ManagedDataAccess.Azure" Version="23.26.300" />
        <PackageReference Include="Oracle.ManagedDataAccess.ConfigFile" Version="23.26.300" />
        <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.300" />
        <PackageReference Include="Oracle.ManagedDataAccess.Kerberos" Version="23.26.300" />
        <PackageReference Include="Oracle.ManagedDataAccess.Oci" Version="23.26.300" />
        <PackageReference Include="RavenDB.Client" Version="7.1.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
        <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.9" />
        <PackageReference Include="Oracle.EntityFrameworkCore" Version="10.23.26300" />
        <PackageReference Include="System.Drawing.Common" Version="10.0.11" />
        <PackageReference Include="System.Formats.Nrbf" Version="10.0.11" />
        <PackageReference Include="System.Security.Permissions" Version="10.0.11" />
        <PackageReference Include="Testcontainers" Version="4.14.0" />
        <PackageReference Include="Testcontainers.CouchDb" Version="4.14.0" />
        <PackageReference Include="Testcontainers.PostgreSql" Version="4.14.0" />
        <PackageReference Include="Testcontainers.MsSql" Version="4.14.0" />
        <PackageReference Include="Testcontainers.MongoDb" Version="4.14.0" />
        <PackageReference Include="Testcontainers.RavenDb" Version="4.10.0" />
        <PackageReference Include="Testcontainers.MySql" Version="4.14.0" />
        <PackageReference Include="Testcontainers.Oracle" Version="4.14.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\x86cc.Benchmarks.Common\x86cc.Benchmarks.Common.csproj" />
    </ItemGroup>

</Project>
