<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
      <PackageReference Include="BenchmarkDotNet.Annotations" Version="0.15.8" />
      <PackageReference Include="RabbitMQ.Client" Version="7.2.2" />
      <PackageReference Include="Testcontainers" Version="4.14.0" />
      <PackageReference Include="Testcontainers.RabbitMq" Version="4.14.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\x86cc.Benchmarks.Common\x86cc.Benchmarks.Common.csproj" />
      <ProjectReference Include="..\x86cc.Benchmarks.TestContainers\x86cc.Benchmarks.TestContainers.csproj" />
    </ItemGroup>

</Project>
