<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\x86cc.Benchmarks.AspNetCore\x86cc.Benchmarks.AspNetCore.csproj" />
      <ProjectReference Include="..\x86cc.Benchmarks.CachingSystems\x86cc.Benchmarks.CachingSystems.csproj" />
      <ProjectReference Include="..\x86cc.Benchmarks.FakeDataGenerators\x86cc.Benchmarks.FakeDataGenerators.csproj" />
      <ProjectReference Include="..\x86cc.Benchmarks.IoCs\x86cc.Benchmarks.IoCs.csproj" />
      <ProjectReference Include="..\x86cc.Benchmarks.Mappers\x86cc.Benchmarks.Mappers.csproj" />
      <ProjectReference Include="..\x86cc.Benchmarks.MessageBrokers\x86cc.Benchmarks.MessageBrokers.csproj" />
      <ProjectReference Include="..\x86cc.Benchmarks.Serializers\x86cc.Benchmarks.Serializers.csproj" />
      <ProjectReference Include="..\x86cc.Benchmarks.DBs\x86cc.Benchmarks.DBs.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="BenchmarkDotNet.Artifacts\" />
    </ItemGroup>

</Project>
